GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsIm5hbWUiOm51bGwsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNjczNDU2NDE5LCJleHAiOjE2NzM0NTY0Mzl9.DA55Oj9fBHjhtWiTp8RDB15MxRcf5BxW1_XjCqZz_rM

###
GET http://localhost:5000/token



###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "andaru akbar",
    "phone_number" : "081232090483",
    "address" : "Jl. Raya Sooko Pulung",
    "email" : "email@gmail.com",
    "password" : "12345678",
    "confPassword" : "12345678"
    
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "email@gmail.com",
    "password" : "12345678"
}
